# config/packages/easy_admin.yaml
easy_admin:
    entities:
        User:
            class: App\Entity\User
            controller: App\Controller\UserAdminController
            form:
                fields:
                    - { property: 'email'}
                    - { property: 'plainPassword', type: 'password', type_options: { required: false }}
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

    design:
       brand_color: 'red'
       menu:
         - { label: "Revenir à l'accueil", route: 'home_index' }
         - { label: "" }
         - { entity: 'User', label: 'Utilisateurs' }

    site_name: 'Administration du site ELBAJA BOXING ACADEMY'





